# This is a basic workflow that is manually triggered

name: Test and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Run tests
      env:
        DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      run: |
        echo "db host : $DATABRICKS_HOST"


